### ISSUE TITLE
Use https

### ISSUE THREAD

**Issue by dominhhai** [ecmascript-daily/ecmascript-daily.github.com#14]
Github page supports `https`. It's nice if you can change the link to `https://ecmascript-daily.github.io/`.
My proxy server do not allow me to access the `http` website.

**Comment by azu** [comment]
I've changed to https as default.

Fix RSS url https://github.com/ecmascript-daily/ecmascript-daily.github.com/commit/0b96d9e7696e6714290261fbeefd92bb9524452c

![ecmascript-daily github com ecmascript daily news 2016-03-27 23-22-30](https://cloud.githubusercontent.com/assets/19714/14065792/caf46046-f472-11e5-8dc2-f4895ffe7c7f.png)

**Comment by dominhhai** [comment]
huge thanks for your kindness!

**Comment by azu** [comment]
☑ [Enforce HTTPS](https://help.github.com/articles/securing-your-github-pages-site-with-https/)
